import { useSelector } from "react-redux";
import { RootState } from "@/app/store/types";

// Language selector hook
export const useLanguage = () => {
  const language = useSelector((state: RootState) => state.language.current);
  return language;
};

// Translation hook
export const useTranslation = () => {
  const language = useSelector((state: RootState) => state.language.current);

  const t = (key: string, params?: Record<string, any>): string => {
    // This is a simplified implementation
    // In a real app, you would load translations from files
    const translations: Record<string, Record<string, string>> = {
      en: {
        "common.save": "Save",
        "common.cancel": "Cancel",
        "common.delete": "Delete",
        "common.edit": "Edit",
        "common.add": "Add",
        "common.search": "Search",
        "common.loading": "Loading...",
        "common.error": "Error",
        "common.success": "Success",
        "common.warning": "Warning",
        "common.info": "Info",
        "common.confirm": "Confirm",
        "common.yes": "Yes",
        "common.no": "No",
        "common.ok": "OK",
        "common.close": "Close",
        "common.back": "Back",
        "common.next": "Next",
        "common.previous": "Previous",
        "common.finish": "Finish",
        "common.continue": "Continue",
        "common.retry": "Retry",
        "common.refresh": "Refresh",
        "common.reset": "Reset",
        "common.clear": "Clear",
        "common.select": "Select",
        "common.selectAll": "Select All",
        "common.deselectAll": "Deselect All",
        "common.filter": "Filter",
        "common.sort": "Sort",
        "common.export": "Export",
        "common.import": "Import",
        "common.download": "Download",
        "common.upload": "Upload",
        "common.print": "Print",
        "common.share": "Share",
        "common.copy": "Copy",
        "common.paste": "Paste",
        "common.cut": "Cut",
        "common.undo": "Undo",
        "common.redo": "Redo",
        "common.help": "Help",
        "common.about": "About",
        "common.settings": "Settings",
        "common.profile": "Profile",
        "common.logout": "Logout",
        "common.login": "Login",
        "common.register": "Register",
        "common.forgotPassword": "Forgot Password",
        "common.resetPassword": "Reset Password",
        "common.changePassword": "Change Password",
        "common.updateProfile": "Update Profile",
        "common.viewProfile": "View Profile",
        "common.editProfile": "Edit Profile",
        "common.deleteProfile": "Delete Profile",
        "common.createAccount": "Create Account",
        "common.activateAccount": "Activate Account",
        "common.deactivateAccount": "Deactivate Account",
        "common.suspendAccount": "Suspend Account",
        "common.unsuspendAccount": "Unsuspend Account",
        "common.blockAccount": "Block Account",
        "common.unblockAccount": "Unblock Account",
        "common.verifyAccount": "Verify Account",
        "common.unverifyAccount": "Unverify Account",
        "common.enableAccount": "Enable Account",
        "common.disableAccount": "Disable Account",
        "common.lockAccount": "Lock Account",
        "common.unlockAccount": "Unlock Account",
        "common.archiveAccount": "Archive Account",
        "common.unarchiveAccount": "Unarchive Account",
        "common.restoreAccount": "Restore Account",
        "common.permanentlyDeleteAccount": "Permanently Delete Account",
        "common.viewDetails": "View Details",
        "common.editDetails": "Edit Details",
        "common.deleteDetails": "Delete Details",
        "common.createDetails": "Create Details",
        "common.updateDetails": "Update Details",
        "common.saveDetails": "Save Details",
        "common.cancelDetails": "Cancel Details",
        "common.confirmDetails": "Confirm Details",
        "common.approveDetails": "Approve Details",
        "common.rejectDetails": "Reject Details",
        "common.pendingDetails": "Pending Details",
        "common.completedDetails": "Completed Details",
        "common.failedDetails": "Failed Details",
        "common.inProgressDetails": "In Progress Details",
        "common.notStartedDetails": "Not Started Details",
        "common.overdueDetails": "Overdue Details",
        "common.dueSoonDetails": "Due Soon Details",
        "common.onTimeDetails": "On Time Details",
        "common.earlyDetails": "Early Details",
        "common.lateDetails": "Late Details",
        "common.highPriorityDetails": "High Priority Details",
        "common.mediumPriorityDetails": "Medium Priority Details",
        "common.lowPriorityDetails": "Low Priority Details",
        "common.criticalPriorityDetails": "Critical Priority Details",
        "common.normalPriorityDetails": "Normal Priority Details",
        "common.urgentPriorityDetails": "Urgent Priority Details",
        "common.lowUrgencyDetails": "Low Urgency Details",
        "common.mediumUrgencyDetails": "Medium Urgency Details",
        "common.highUrgencyDetails": "High Urgency Details",
        "common.criticalUrgencyDetails": "Critical Urgency Details",
        "common.normalUrgencyDetails": "Normal Urgency Details",
        "common.urgentUrgencyDetails": "Urgent Urgency Details",
        // Add namespace-specific translations
        "otp.title": "OTP Verification",
        "otp.description": "Please enter the OTP code",
        "otp.resend": "Resend OTP",
        "otp.verify": "Verify",
        "validation.required": "This field is required",
        "validation.invalid": "Invalid value",
        "validation.minLength": "Minimum length is {min}",
        "validation.maxLength": "Maximum length is {max}",
        "searchQuick.title": "Quick Search",
        "searchQuick.placeholder": "Search...",
        "searchQuick.quickAccess": "Quick Access",
        "searchQuick.ticker": "Ticker",
      },
      vi: {
        "common.save": "Lưu",
        "common.cancel": "Hủy",
        "common.delete": "Xóa",
        "common.edit": "Sửa",
        "common.add": "Thêm",
        "common.search": "Tìm kiếm",
        "common.loading": "Đang tải...",
        "common.error": "Lỗi",
        "common.success": "Thành công",
        "common.warning": "Cảnh báo",
        "common.info": "Thông tin",
        "common.confirm": "Xác nhận",
        "common.yes": "Có",
        "common.no": "Không",
        "common.ok": "OK",
        "common.close": "Đóng",
        "common.back": "Quay lại",
        "common.next": "Tiếp theo",
        "common.previous": "Trước đó",
        "common.finish": "Hoàn thành",
        "common.continue": "Tiếp tục",
        "common.retry": "Thử lại",
        "common.refresh": "Làm mới",
        "common.reset": "Đặt lại",
        "common.clear": "Xóa",
        "common.select": "Chọn",
        "common.selectAll": "Chọn tất cả",
        "common.deselectAll": "Bỏ chọn tất cả",
        "common.filter": "Lọc",
        "common.sort": "Sắp xếp",
        "common.export": "Xuất",
        "common.import": "Nhập",
        "common.download": "Tải xuống",
        "common.upload": "Tải lên",
        "common.print": "In",
        "common.share": "Chia sẻ",
        "common.copy": "Sao chép",
        "common.paste": "Dán",
        "common.cut": "Cắt",
        "common.undo": "Hoàn tác",
        "common.redo": "Làm lại",
        "common.help": "Trợ giúp",
        "common.about": "Giới thiệu",
        "common.settings": "Cài đặt",
        "common.profile": "Hồ sơ",
        "common.logout": "Đăng xuất",
        "common.login": "Đăng nhập",
        "common.register": "Đăng ký",
        "common.forgotPassword": "Quên mật khẩu",
        "common.resetPassword": "Đặt lại mật khẩu",
        "common.changePassword": "Đổi mật khẩu",
        "common.updateProfile": "Cập nhật hồ sơ",
        "common.viewProfile": "Xem hồ sơ",
        "common.editProfile": "Sửa hồ sơ",
        "common.deleteProfile": "Xóa hồ sơ",
        "common.createAccount": "Tạo tài khoản",
        "common.activateAccount": "Kích hoạt tài khoản",
        "common.deactivateAccount": "Vô hiệu hóa tài khoản",
        "common.suspendAccount": "Tạm ngưng tài khoản",
        "common.unsuspendAccount": "Bỏ tạm ngưng tài khoản",
        "common.blockAccount": "Chặn tài khoản",
        "common.unblockAccount": "Bỏ chặn tài khoản",
        "common.verifyAccount": "Xác minh tài khoản",
        "common.unverifyAccount": "Bỏ xác minh tài khoản",
        "common.enableAccount": "Kích hoạt tài khoản",
        "common.disableAccount": "Vô hiệu hóa tài khoản",
        "common.lockAccount": "Khóa tài khoản",
        "common.unlockAccount": "Mở khóa tài khoản",
        "common.archiveAccount": "Lưu trữ tài khoản",
        "common.unarchiveAccount": "Bỏ lưu trữ tài khoản",
        "common.restoreAccount": "Khôi phục tài khoản",
        "common.permanentlyDeleteAccount": "Xóa vĩnh viễn tài khoản",
        "common.viewDetails": "Xem chi tiết",
        "common.editDetails": "Sửa chi tiết",
        "common.deleteDetails": "Xóa chi tiết",
        "common.createDetails": "Tạo chi tiết",
        "common.updateDetails": "Cập nhật chi tiết",
        "common.saveDetails": "Lưu chi tiết",
        "common.cancelDetails": "Hủy chi tiết",
        "common.confirmDetails": "Xác nhận chi tiết",
        "common.approveDetails": "Phê duyệt chi tiết",
        "common.rejectDetails": "Từ chối chi tiết",
        "common.pendingDetails": "Chi tiết đang chờ",
        "common.completedDetails": "Chi tiết đã hoàn thành",
        "common.failedDetails": "Chi tiết thất bại",
        "common.inProgressDetails": "Chi tiết đang thực hiện",
        "common.notStartedDetails": "Chi tiết chưa bắt đầu",
        "common.overdueDetails": "Chi tiết quá hạn",
        "common.dueSoonDetails": "Chi tiết sắp đến hạn",
        "common.onTimeDetails": "Chi tiết đúng hạn",
        "common.earlyDetails": "Chi tiết sớm",
        "common.lateDetails": "Chi tiết muộn",
        "common.highPriorityDetails": "Chi tiết ưu tiên cao",
        "common.mediumPriorityDetails": "Chi tiết ưu tiên trung bình",
        "common.lowPriorityDetails": "Chi tiết ưu tiên thấp",
        "common.criticalPriorityDetails": "Chi tiết ưu tiên nghiêm trọng",
        "common.normalPriorityDetails": "Chi tiết ưu tiên bình thường",
        "common.urgentPriorityDetails": "Chi tiết ưu tiên khẩn cấp",
        "common.lowUrgencyDetails": "Chi tiết khẩn cấp thấp",
        "common.mediumUrgencyDetails": "Chi tiết khẩn cấp trung bình",
        "common.highUrgencyDetails": "Chi tiết khẩn cấp cao",
        "common.criticalUrgencyDetails": "Chi tiết khẩn cấp nghiêm trọng",
        "common.normalUrgencyDetails": "Chi tiết khẩn cấp bình thường",
        "common.urgentUrgencyDetails": "Chi tiết khẩn cấp khẩn cấp",
        // Add namespace-specific translations
        "otp.title": "Xác thực OTP",
        "otp.description": "Vui lòng nhập mã OTP",
        "otp.resend": "Gửi lại OTP",
        "otp.verify": "Xác thực",
        "validation.required": "Trường này là bắt buộc",
        "validation.invalid": "Giá trị không hợp lệ",
        "validation.minLength": "Độ dài tối thiểu là {min}",
        "validation.maxLength": "Độ dài tối đa là {max}",
        "searchQuick.title": "Tìm kiếm nhanh",
        "searchQuick.placeholder": "Tìm kiếm...",
        "searchQuick.quickAccess": "Truy cập nhanh",
        "searchQuick.ticker": "Mã cổ phiếu",
      },
    };

    let translation = translations[language]?.[key] || key;

    if (params) {
      Object.entries(params).forEach(([paramKey, paramValue]) => {
        translation = translation.replace(`{${paramKey}}`, String(paramValue));
      });
    }

    return translation;
  };

  return { t, language };
};

// Additional language hooks
export const useNSTranslate = (namespace?: string) => {
  const { t } = useTranslation();

  const nsTranslate = (key: string, params?: Record<string, any>): string => {
    const fullKey = namespace ? `${namespace}.${key}` : key;
    return t(fullKey, params);
  };

  return nsTranslate;
};
